### ISSUE TITLE
Add a 'question' issue template

### ISSUE THREAD

**Issue by ApplicationCoding** [ApplicationCoding/console-calculator#21]
This can be helpful for those who have questions about Calculator. @YojanProductions, please check this file as your guide for this task: https://github.com/ApplicationCoding/calculator/blob/question_issue_template/question_issue_template_for_YojanProductions'%20Task.txt

**Comment by ApplicationCoding** [comment]
Are you doing it?

**Comment by ApplicationCoding** [comment]
Please click the link sent with the description @YojanProductions. Just chat me if still struggling.

**Comment by ApplicationCoding** [comment]
Re-assigned to @MKilo24

**Comment by MKilo24** [comment]
Maybe it's better to ask questions on **Discussions**?

**Comment by ApplicationCoding** [comment]
> Maybe it's better to ask questions on **Discussions**?

Yes, I think that's better.
