### ISSUE TITLE
Seperate updates into 3 different groups

### ISSUE THREAD

**Issue by ApplicationCoding** [ApplicationCoding/console-calculator#28]
Updates will be separated into 3 different groups. The first one is **Bug Fixes**, the second one, **Updates**, and the last one, **New Features**.

**Comment by MKilo24** [comment]
I changed **Updates** to **Updates and Improvements** instead for the [v1.6.1 Alpha](https://github.com/ApplicationCoding/console-calculator/releases/tag/v1.6.1) version.

**Comment by ApplicationCoding** [comment]
Okay, I think that's good👍
