### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by MKilo24** [ApplicationCoding/console-calculator#34]
Update the documentation for new information that's not in it. If no changes are needed, please close this issue immediately.

**Comment by ApplicationCoding** [comment]
Just added an extra change:
From ``The current version of Calculator: v1.6.1`` to ``The current version of Console Calculator: v1.6.1``

**Comment by ApplicationCoding** [comment]
Done. I didn't have to update the documentation except for some clarity changes which makes it easier to understand. I also updated some texts that still show as **Calculator** and changed it to **Console Calculator.** The sentence **The latest version is v1.6.0** to **The latest version is 1.6.1.**

These are all the changes I've made to the documentation.

**Comment by MKilo24** [comment]
Nice changes!
